service: real-state-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: 'us-east-2'
  stage: ${opt:stage, 'prod'}

  apiGateway:
    apiKeys:
      - real-state-api-key-${self:provider.stage}  # Serverless crea ApiKey y UsagePlan automáticamente

  environment:
    STAGE: ${self:provider.stage}
    DEBUG: false
    DATABASE_URL: ${env:DATABASE_URL}
    VPC_SECURITY_GROUP_ID: ${env:VPC_SECURITY_GROUP_ID}
    VPC_SUBNET_ID_1: ${env:VPC_SUBNET_ID_1}
    VPC_SUBNET_ID_2: ${env:VPC_SUBNET_ID_2}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

  memorySize: 512
  timeout: 30
  logRetentionInDays: 14

functions:
  api:
    handler: app.main.handler
    events:
      # Search endpoint
      - http:
          path: /api/v1/search/general
          method: POST
          cors: true
          private: true

plugins:
  - serverless-python-requirements

vpc:
  securityGroupIds:
    - ${env:VPC_SECURITY_GROUP_ID, 'sg-0123456789abcdef0'}
  subnetIds:
    - ${env:VPC_SUBNET_ID_1, 'subnet-0123456789abcdef0'}
    - ${env:VPC_SUBNET_ID_2, 'subnet-0123456789abcdef1'}


custom:
  pythonRequirements:
    dockerizePip: non-linux
    requirementsFile: requirements-prod.txt
    noDeploy:
      - black
      - isort
      - flake8
      - mypy
      - pre-commit
      - pytest
      - pytest-*
      - coverage
    zip: false
    slim: false
    usePoetry: false
    useStaticCache: false
    useDownloadCache: false
